package hibernate;
// Generated 10-gen-2019 17.04.43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Destination generated by hbm2java
 */
public class Destination  implements java.io.Serializable {


     private int destinationId;
     private String name;
     private String description;
     private String imagePath;
     private Set<Package> packages = new HashSet<Package>(0);
     private Set<Experience> experiences = new HashSet<Experience>(0);

    public Destination() {
    }

	
    public Destination(int destinationId, String name, String description) {
        this.destinationId = destinationId;
        this.name = name;
        this.description = description;
    }
    public Destination(int destinationId, String name, String description, String imagePath, Set<Package> packages, Set<Experience> experiences) {
       this.destinationId = destinationId;
       this.name = name;
       this.description = description;
       this.imagePath = imagePath;
       this.packages = packages;
       this.experiences = experiences;
    }
   
    public int getDestinationId() {
        return this.destinationId;
    }
    
    public void setDestinationId(int destinationId) {
        this.destinationId = destinationId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public Set<Package> getPackages() {
        return this.packages;
    }
    
    public void setPackages(Set<Package> packages) {
        this.packages = packages;
    }
    public Set<Experience> getExperiences() {
        return this.experiences;
    }
    
    public void setExperiences(Set<Experience> experiences) {
        this.experiences = experiences;
    }




}


