package hibernate;
// Generated 7-gen-2019 21.46.25 by Hibernate Tools 4.3.1



/**
 * Experience generated by hbm2java
 */
public class Experience  implements java.io.Serializable {


     private int experienceId;
     private Destination destination;
     private Package pack;
     private String name;
     private boolean isExtra;
     private String description;

    public Experience() {
    }

	
    public Experience(int experienceId, Destination destination, String name, boolean isExtra, String description) {
        this.experienceId = experienceId;
        this.destination = destination;
        this.name = name;
        this.isExtra = isExtra;
        this.description = description;
    }
    public Experience(int experienceId, Destination destination, Package pack, String name, boolean isExtra, String description) {
       this.experienceId = experienceId;
       this.destination = destination;
       this.pack = pack;
       this.name = name;
       this.isExtra = isExtra;
       this.description = description;
    }
   
    public int getExperienceId() {
        return this.experienceId;
    }
    
    public void setExperienceId(int experienceId) {
        this.experienceId = experienceId;
    }
    public Destination getDestination() {
        return this.destination;
    }
    
    public void setDestination(Destination destination) {
        this.destination = destination;
    }
    public Package getPackage() {
        return this.pack;
    }
    
    public void setPackage(Package pack) {
        this.pack = pack;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsExtra() {
        return this.isExtra;
    }
    
    public void setIsExtra(boolean isExtra) {
        this.isExtra = isExtra;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


