package hibernate;
// Generated 7-gen-2019 12.19.03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Extra generated by hbm2java
 */
public class Extra  implements java.io.Serializable {


     private Integer extraId;
     private Package pack;
     private String name;
     private String description;
     private BigDecimal price;

    public Extra() {
    }

	
    public Extra(String name, String description, BigDecimal price) {
        this.name = name;
        this.description = description;
        this.price = price;
    }
    public Extra(Package pack, String name, String description, BigDecimal price) {
       this.pack = pack;
       this.name = name;
       this.description = description;
       this.price = price;
    }
   
    public Integer getExtraId() {
        return this.extraId;
    }
    
    public void setExtraId(Integer extraId) {
        this.extraId = extraId;
    }
    public Package getPackage() {
        return this.pack;
    }
    
    public void setPackage(Package pack) {
        this.pack = pack;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


