package hibernate;
// Generated 7-gen-2019 21.46.25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private User user;
     private BigDecimal price;
     private Date date;
     private boolean isPaid;
     private String billingFirstName;
     private String billingLastName;
     private String billingAddressStreet;
     private String billingAddressZipCode;
     private String billingAddressCity;
     private String billingAddressCountry;
     private Set<Package> packages = new HashSet<Package>(0);

    public Order() {
    }

	
    public Order(User user, BigDecimal price, Date date, boolean isPaid) {
        this.user = user;
        this.price = price;
        this.date = date;
        this.isPaid = isPaid;
    }
    public Order(User user, BigDecimal price, Date date, boolean isPaid, String billingFirstName, String billingLastName, String billingAddressStreet, String billingAddressZipCode, String billingAddressCity, String billingAddressCountry, Set<Package> packages) {
       this.user = user;
       this.price = price;
       this.date = date;
       this.isPaid = isPaid;
       this.billingFirstName = billingFirstName;
       this.billingLastName = billingLastName;
       this.billingAddressStreet = billingAddressStreet;
       this.billingAddressZipCode = billingAddressZipCode;
       this.billingAddressCity = billingAddressCity;
       this.billingAddressCountry = billingAddressCountry;
       this.packages = packages;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public boolean isIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(boolean isPaid) {
        this.isPaid = isPaid;
    }
    public String getBillingFirstName() {
        return this.billingFirstName;
    }
    
    public void setBillingFirstName(String billingFirstName) {
        this.billingFirstName = billingFirstName;
    }
    public String getBillingLastName() {
        return this.billingLastName;
    }
    
    public void setBillingLastName(String billingLastName) {
        this.billingLastName = billingLastName;
    }
    public String getBillingAddressStreet() {
        return this.billingAddressStreet;
    }
    
    public void setBillingAddressStreet(String billingAddressStreet) {
        this.billingAddressStreet = billingAddressStreet;
    }
    public String getBillingAddressZipCode() {
        return this.billingAddressZipCode;
    }
    
    public void setBillingAddressZipCode(String billingAddressZipCode) {
        this.billingAddressZipCode = billingAddressZipCode;
    }
    public String getBillingAddressCity() {
        return this.billingAddressCity;
    }
    
    public void setBillingAddressCity(String billingAddressCity) {
        this.billingAddressCity = billingAddressCity;
    }
    public String getBillingAddressCountry() {
        return this.billingAddressCountry;
    }
    
    public void setBillingAddressCountry(String billingAddressCountry) {
        this.billingAddressCountry = billingAddressCountry;
    }
    public Set<Package> getPackages() {
        return this.packages;
    }
    
    public void setPackages(Set<Package> packages) {
        this.packages = packages;
    }




}


