package hibernate;
// Generated 5-gen-2019 19.39.33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "vr_vacation", uniqueConstraints = {
		@UniqueConstraint(columnNames = "price"),
                @UniqueConstraint(columnNames = "date"),
                @UniqueConstraint(columnNames = "status"),
                @UniqueConstraint(columnNames = "billing_first_name"),
                @UniqueConstraint(columnNames = "billing_last_name"),
                @UniqueConstraint(columnNames = "billing_address_street"),
                @UniqueConstraint(columnNames = "billing_address_zipcode"),
                @UniqueConstraint(columnNames = "billing_address_city"),
                @UniqueConstraint(columnNames = "billing_address_country"),
})
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private User user;
     private BigDecimal price;
     private Date date;
     private String status;
     private String billingFirstName;
     private String billingLastName;
     private String billingAddressStreet;
     private String billingAddressZipCode;
     private String billingAddressCity;
     private String billingAddressCountry;
     private Set<Package> packages = new HashSet<Package>(0);

    public Order() {
    }

	
    public Order(User user, BigDecimal price, Date date, String status) {
        this.user = user;
        this.price = price;
        this.date = date;
        this.status = status;
    }
    public Order(User user, BigDecimal price, Date date, String status, String billingFirstName, String billingLastName, String billingAddressStreet, String billingAddressZipCode, String billingAddressCity, String billingAddressCountry, Set<Package> packages) {
       this.user = user;
       this.price = price;
       this.date = date;
       this.status = status;
       this.billingFirstName = billingFirstName;
       this.billingLastName = billingLastName;
       this.billingAddressStreet = billingAddressStreet;
       this.billingAddressZipCode = billingAddressZipCode;
       this.billingAddressCity = billingAddressCity;
       this.billingAddressCountry = billingAddressCountry;
       this.packages = packages;
    }
   
     @Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_id", unique = true, nullable = false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBillingFirstName() {
        return this.billingFirstName;
    }
    
    public void setBillingFirstName(String billingFirstName) {
        this.billingFirstName = billingFirstName;
    }
    public String getBillingLastName() {
        return this.billingLastName;
    }
    
    public void setBillingLastName(String billingLastName) {
        this.billingLastName = billingLastName;
    }
    public String getBillingAddressStreet() {
        return this.billingAddressStreet;
    }
    
    public void setBillingAddressStreet(String billingAddressStreet) {
        this.billingAddressStreet = billingAddressStreet;
    }
    public String getBillingAddressZipCode() {
        return this.billingAddressZipCode;
    }
    
    public void setBillingAddressZipCode(String billingAddressZipCode) {
        this.billingAddressZipCode = billingAddressZipCode;
    }
    public String getBillingAddressCity() {
        return this.billingAddressCity;
    }
    
    public void setBillingAddressCity(String billingAddressCity) {
        this.billingAddressCity = billingAddressCity;
    }
    public String getBillingAddressCountry() {
        return this.billingAddressCountry;
    }
    
    public void setBillingAddressCountry(String billingAddressCountry) {
        this.billingAddressCountry = billingAddressCountry;
    }
    
    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "order_has_package", catalog = "vr_vacation", joinColumns = { 
			@JoinColumn(name = "order_id", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "package_id", 
					nullable = false, updatable = false) })
    public Set<Package> getPackages() {
        return this.packages;
    }
    
    public void setPackages(Set<Package> packages) {
        this.packages = packages;
    }




}


