package hibernate;
// Generated 1-gen-2019 19.29.32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private User user;
     private BigDecimal price;
     private Date date;
     private String status;
     private String billingFirstName;
     private String billingLastName;
     private String billingAddressStreet;
     private String billingAddressZipCode;
     private String billingAddressCity;
     private String billingAddressCountry;

    public Order() {
    }

	
    public Order(User user, BigDecimal price, Date date, String status) {
        this.user = user;
        this.price = price;
        this.date = date;
        this.status = status;
    }
    public Order(User user, BigDecimal price, Date date, String status, String billingFirstName, String billingLastName, String billingAddressStreet, String billingAddressZipCode, String billingAddressCity, String billingAddressCountry) {
       this.user = user;
       this.price = price;
       this.date = date;
       this.status = status;
       this.billingFirstName = billingFirstName;
       this.billingLastName = billingLastName;
       this.billingAddressStreet = billingAddressStreet;
       this.billingAddressZipCode = billingAddressZipCode;
       this.billingAddressCity = billingAddressCity;
       this.billingAddressCountry = billingAddressCountry;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBillingFirstName() {
        return this.billingFirstName;
    }
    
    public void setBillingFirstName(String billingFirstName) {
        this.billingFirstName = billingFirstName;
    }
    public String getBillingLastName() {
        return this.billingLastName;
    }
    
    public void setBillingLastName(String billingLastName) {
        this.billingLastName = billingLastName;
    }
    public String getBillingAddressStreet() {
        return this.billingAddressStreet;
    }
    
    public void setBillingAddressStreet(String billingAddressStreet) {
        this.billingAddressStreet = billingAddressStreet;
    }
    public String getBillingAddressZipCode() {
        return this.billingAddressZipCode;
    }
    
    public void setBillingAddressZipCode(String billingAddressZipCode) {
        this.billingAddressZipCode = billingAddressZipCode;
    }
    public String getBillingAddressCity() {
        return this.billingAddressCity;
    }
    
    public void setBillingAddressCity(String billingAddressCity) {
        this.billingAddressCity = billingAddressCity;
    }
    public String getBillingAddressCountry() {
        return this.billingAddressCountry;
    }
    
    public void setBillingAddressCountry(String billingAddressCountry) {
        this.billingAddressCountry = billingAddressCountry;
    }




}


